# Generated by Django 5.2 on 2025-05-29 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("lists", "0004_item_list"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="item",
            unique_together={("text", "list")},
        ),
    ]
