# Generated by Django 5.2 on 2025-06-12 02:17

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_token"),
    ]

    operations = [
        migrations.AlterField(
            model_name="token",
            name="uid",
            field=models.CharField(default=uuid.uuid4, max_length=40),
        ),
    ]
